using SportsCardStore.Core.Enums;

namespace SportsCardStore.Shared.Models
{
    /// <summary>
    /// Structured card listing generated by the Card Listing Agent.
    /// Contains AI-generated title, description, suggested price, tags, and category.
    /// </summary>
    public class CardListing
    {
        /// <summary>
        /// Concise, professional title for the card listing (max 200 characters)
        /// </summary>
        public string Title { get; set; } = string.Empty;

        /// <summary>
        /// Detailed description including condition, features, and collector appeal (max 2000 characters)
        /// </summary>
        public string Description { get; set; } = string.Empty;

        /// <summary>
        /// AI-suggested listing price in USD based on current market conditions
        /// </summary>
        public decimal SuggestedPrice { get; set; }

        /// <summary>
        /// Relevant search tags to improve discoverability
        /// </summary>
        public List<string> Tags { get; set; } = new();

        /// <summary>
        /// Sport category (Baseball, Football, Basketball, Hockey)
        /// </summary>
        public Category Category { get; set; }
    }
}
